### ISSUE TITLE
Error upgrading to version 2.0.1

### ISSUE THREAD

**Issue by ashokgelal** [eidellev/inertiajs-adonisjs#1]
I just tried upgrading from version 1.0.1 to the latest 2.0.1 and ran into `ERESOLVE unable to resolve dependency tree` issue. I doubt if this has to do with the fact that this package seems to depend on both @adonis/config 3.x and 2.x: https://github.com/eidellev/inertiajs-adonisjs/blob/main/package.json#L51

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cleavr@1.0.0
npm ERR! Found: @adonisjs/config@3.0.0
npm ERR! node_modules/@adonisjs/config
npm ERR!   dev @adonisjs/config@"^3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @adonisjs/config@"^2.0.3" from @eidellev/inertia-adonisjs@2.0.1
npm ERR! node_modules/@eidellev/inertia-adonisjs
npm ERR!   @eidellev/inertia-adonisjs@"^2.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**Comment by eidellev** [comment]
Hi @ashokgelal
Thank you for reporting this issue 👍 
I've release `v2.0.2` that updates the package's dependence on `@adonisjs/config` to `^3.0.0`.

Let me know if it helped. If not, let I'll try to dig a little deeper later today.

**Comment by ashokgelal** [comment]
Unfortunately, no luck (in my case). I've the latest `"@adonisjs/core": "^5.0.5-canary-rc-2"` installed while this package is looking for `@adonisjs/core@"^5.0.1"`:

```
npm ERR! Found: @adonisjs/core@5.0.5-canary-rc-2
npm ERR! node_modules/@adonisjs/core
npm ERR!   @adonisjs/core@"^5.0.5-canary-rc-2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @adonisjs/core@"^5.0.1" from @eidellev/inertia-adonisjs@2.0.2
npm ERR! node_modules/@eidellev/inertia-adonisjs
npm ERR!   @eidellev/inertia-adonisjs@"^2.0.2" from the root project
```

**Comment by eidellev** [comment]
Ok, that kinda makes sense. I'll try to reproduce this later tonight.
Can you please share all adonis packages and their versions that you're using?

**Comment by ashokgelal** [comment]
Here are some of the Adonis related packages:

Dependencies:

```
    "@adonisjs/application": "^4.0.4",
    "@adonisjs/auth": "^6.0.1",
    "@adonisjs/core": "^5.0.5-canary-rc-2",
    "@adonisjs/lucid": "^11.0.1",
    "@adonisjs/repl": "^2.0.1",
    "@adonisjs/session": "^5.0.0",
    "@adonisjs/shield": "^5.0.0",
    "@adonisjs/view": "^4.0.0",
```

Dev Dependencies:
```
    "@adonisjs/assembler": "^4.0.1",
    "@adonisjs/config": "^3.0.0",
```

**Comment by eidellev** [comment]
@ashokgelal sorry for the long wait.  Please see if upgrading to `v2.1.0` resolved your issue.

**Comment by eidellev** [comment]
Closing this issue for now

**Comment by eidellev** [comment]
Closing this issue for now
