### ISSUE TITLE
How to resolve ESlint to work with vue extension?

### ISSUE THREAD

**Issue by marcelodelta** [eidellev/inertiajs-adonisjs#103]
Parsing error: ESLint was configured to run on `<tsconfigRootDir>/resources\js\Pages\Home.vue` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
The extension for the file (`.vue`) is non-standard. You should add `parserOptions.extraFileExtensions` to your config.

**Comment by eidellev** [comment]
Hi @marcelodelta 
This is a bit out of the scope of this library. What I personally do in my projects is to have a separate `tsconfig.json` and `eslint` configs for my client code and for my server.

See [this](https://eslint.vuejs.org/) for how to set up eslint with Vue.
