### ISSUE TITLE
[Question] How to set css classes as active on the current link.

### ISSUE THREAD

**Issue by prpanto** [eidellev/inertiajs-adonisjs#107]
Hello, thank for this.
This is the first time I use adonis and inertia. In laravel and inertia we use "route" method witch can tell the link is active, For example I want to set some classes and tell they will be active on the current url. How to implement here with adonis and inertia?

**Comment by WeyIin** [comment]
Check this out - https://github.com/eidellev/adonis-stardust

**Comment by eidellev** [comment]
@prpanto thank you :-)
please see @WeyIin 's answer
