### ISSUE TITLE
Support Inertia 1.0

### ISSUE THREAD

**Issue by lindgr3n** [eidellev/inertiajs-adonisjs#108]
Hi! Is there any plan on updating to support Inertia 1.0?

**Comment by eidellev** [comment]
Hey @lindgr3n 
Abosolutely! I'm a bit swamped at the moment, but I am definitely planning to upgrade to Inertia v1.0.

**Comment by lindgr3n** [comment]
Great 👍 Looking forward to it :)

**Comment by ralphdas** [comment]
The 1.0 release has a lot of enhancements and there seems no way to check older pre 1.0 documentation of platform specific providers like inertia-react. So staying up to date would be great.

**Comment by eidellev** [comment]
Done.
Starting from v8.0.0 `inertiajs-adonisjs` will setup inertia for you based on the latest changes in inertia v1.

Important note: it seem the inertia team changed all their packages from CJS to ESM. overall it is a good thing, but this will invetibaly break things for end users so be advised.

**Comment by ralphdas** [comment]
Great does this mean that we will have to wait for AdonisJS to fully support ESM modules or is it just changing some Webpack Encore settings?

**Comment by eidellev** [comment]
Most things will probably be resolved by configuring Encore, but SSR will likely break until Adonis support ESM completely (At least as it's currently implemented)

**Comment by ralphdas** [comment]
Could you give a example/ hint about how to update the config. After updating a codebase I keep on bumping into the fact that the AdonisJS package.json specifies 'commonjs' and now inertiajs/react is ESM, resulting in the expected: "caught ReferenceError: module is not defined"
