### ISSUE TITLE
Error when trying to install it

### ISSUE THREAD

**Issue by wfelipe99** [eidellev/inertiajs-adonisjs#12]
I'm trying to install it, but I can't. I'm getting a `npm ERR! Failed at the @eidellev/inertia-adonisjs@2.2.0 postinstall script`.

I created a fresh Adonis project using `npm init adonis-ts-app` and tried to `npm i @eidellev/inertia-adonisjs`. But I get the error above.

Here's the full npm log:

https://pastebin.com/fsrF54UX

**Comment by eidellev** [comment]
@wfelipe99 thank you for reporting this issue! 
I've release `v2.2.2` that resolved this problem. 
For the sake of transparency, the issue was with a lingering postinstall script that initializes husky. I've recently switched from `yarn` to `npm` and forgot to remove it.
