### ISSUE TITLE
Use qs to preserve querystring

### ISSUE THREAD

**Issue by arthur-er** [eidellev/inertiajs-adonisjs#125]
Using only encode doesn't have full compatibility with all querystrings, AdonisJS uses [`qs`](https://www.npmjs.com/package/qs) under the hood, so we should use it here too

**Comment by eidellev** [comment]
Hey @arthur-er  :-)
Can you provide a bit more context on what isn't working as you expect?

**Comment by arthur-er** [comment]
> Hey @arthur-er :-) Can you provide a bit more context on what isn't working as you expect?

Array serialization on querystrings for example

Passing `array[]=1&array[]=2` results in a invalid encode using `querystring` , resulting in a valid request to adonis, but not properly updating the frontend url.
