### ISSUE TITLE
Deprecated Warning: container.with() is deprecated. Use container.withBindings()

### ISSUE THREAD

**Issue by ashokgelal** [eidellev/inertiajs-adonisjs#23]
I noticed that there is already a todo here: https://github.com/eidellev/inertiajs-adonisjs/blob/main/providers/InertiaProvider/InertiaProvider.ts#L128

It'd be nice to take care of the warning now that Adonis is out of preview :)

**Comment by eidellev** [comment]
Thanks! I'll definitely implemented it in the next release. I was putting it off since it's a breaking change.
