### ISSUE TITLE
Metadata param in Route Helper

### ISSUE THREAD

**Issue by Dolu89** [eidellev/inertiajs-adonisjs#26]
I can't find a solution to add metadata (for root Edge file) in Route Helper 

``` html
<meta name="twitter:title" content="{{ page.title }}">
```

Maybe this signature could be added
``` js
// /start/routes.ts
import Route from '@ioc:Adonis/Core/Route';

Route.inertia('about', 'About', { metadata: '...' });
```

Any advice or solution?

**Comment by eidellev** [comment]
Hey @Dolu89 !
Thanks for bringing it up. This isn't currently supported, but I will add it in the next release.
