### ISSUE TITLE
Is there way to define multiple app.edge views?

### ISSUE THREAD

**Issue by jakemake** [eidellev/inertiajs-adonisjs#27]
Hello, thanks for this plugin.
I want to set multiple edge entrypoints, is there way to do this?
For example app.edge for public and admin.edge for admin with own webpack encore assets ?

**Comment by eidellev** [comment]
Hi @jakemake ! Thanks for the feedback.
One of my goals with this project is to mimic the official laravel adapter as closely as possible and as far as I know configuring multiple views isn't supported.
I'm curious about your requirement though. Are you concerned about bundle size?
If so, using dynamic imports/lazy loading and configuring `encore` to split your code into multiple chunks should do the trick.

**Comment by jakemake** [comment]
Thanks for your answer. Yeah, i just want to use "heavy" UI kit for admin, another ui for public, and i don't want to mix it all in one file

**Comment by eidellev** [comment]
Makes sense. Another option is to have multiple entrypoints in webpack and then select the correct one inside the view.
Something like this:
```blade
@if(some condition)
  <script src="{{ asset('assets/app.js') }}" defer></script>
@else
  <script src="{{ asset('assets/admin.js') }}" defer></script>
```
