### ISSUE TITLE
Plain json issue

### ISSUE THREAD

**Issue by jakemake** [eidellev/inertiajs-adonisjs#28]
I launched my project to production recently and i faced issue returning plain/json text instead of rendered page on mobile android/chrome. I also tried to kind of reproduce it on dev server (new project and my existing project) and it confirms on localhost

Steps to reproduce it on mobile:
1.Visit app, 
2. click on inertia link
3. after page was rendered try to close all apps in android (throught the "recent apps" button from android system navigation)
4. Open Chrome again
![image](https://user-images.githubusercontent.com/22964241/128984139-f89f0e17-d712-4746-b021-f2748a9d9b3e.png)

It's not necessary to close, you can actually minimize the browser, try use other apps then open it again

Steps to reproduce it on dev server (in my case PC/Windows)
1.Visit app on Chrome
2. Click inertia-link
3. Kill Google Chrome browser process from task manager
4. Open Chrome again, Chrome will suggest you to restore unexpedetly closed tabs. Restore it and you will see plain json response
5. application renders properly only after you reload the page in browser 

![image](https://user-images.githubusercontent.com/22964241/128983662-7cc662ca-73e0-4572-9c56-7fd284a2f2ae.png)

**Comment by eidellev** [comment]
Thanks for reporting this issue :-)
I'll take a look

**Comment by eidellev** [comment]
Fixed in `v4.0.1`
Let me know if you run into any other issues and thanks again!

**Comment by jakemake** [comment]
Now it works properly. Thanks @eidellev for fix!
