### ISSUE TITLE
Adonis routes in the frontend view

### ISSUE THREAD

**Issue by segungreat** [eidellev/inertiajs-adonisjs#33]
Is there a way to generate and use the adonisjs routes in the view. Like ziggy for laravel where there is a global $routes. Is there any option or available package similar to this or any other way to make it work.
Thanks

**Comment by eidellev** [comment]
Hey @segungreat ! 
I couldn't find anything like that either, so I started working on a ziggy clone for adonis called stardust ⭐ 
I'll try to publish something over the weekend, but in the meanwhile you can monitor my progress here:
https://github.com/eidellev/adonis-stardust
(sorry, no readme yet)

**Comment by eidellev** [comment]
Just published the first version here:
https://www.npmjs.com/package/@eidellev/adonis-stardust

**Comment by xewl** [comment]
Not to bump this, but I noticed the readme of this repo contained "stardust" in 1 code instance (for route params), and it might be helpful to extend the readme somewhat so it's clear this is an extra dependency and why it'd be worth adding too.
