### ISSUE TITLE
Intercept All Inertia requests must receive a valid Inertia response

### ISSUE THREAD

**Issue by anishghimire862** [eidellev/inertiajs-adonisjs#36]
Hello,

Is there a way I can intercept All Inertia requests must receive a valid Inertia response errors and perform some tasks? Actually I am trying to log errors to some crash reporting platform. I am able to catch and log errors with status 400 and 500 but since All Inertia requests must receive a valid Inertia response, has a status code of 200-300 I am not able to capture such errors.

Any help will be appreciated. 

Thank you.

**Comment by anishghimire862** [comment]
I think it is neither Inertia nor InertiaAdonis's fault. Inertia is just getting a non-json response and doesn't know what to do with it. So my controller should probably do a better job of returning the right response based on the situation.

If I am able to repro it I will write a controller and share it here,

Thank you for your time.

**Comment by eidellev** [comment]
Thanks! I'm closing this issue for now, but please keep me posted if you run into any other issues.
