### ISSUE TITLE
How to add type definition for shared data

### ISSUE THREAD

**Issue by eokwukwe** [eidellev/inertiajs-adonisjs#43]
Hello @eidellev. Thank you for this wonderful package. I am using it with Vue 3 and Typescript. I can't find how to add type definitions for shared data. 

Although it is working, Typescript is complaining that those properties are `unknown` and I don't get suggestions.

How can I add type definitions for shared data?

**Comment by eidellev** [comment]
Hi @eokwukwe .
Thank you for opening this issue. I'm not using Vue myself, so I'm not sure about this, but I think you can just type shared data the same way you type regular page props. At least that's the way it is done with react:
![image](https://user-images.githubusercontent.com/11258756/142655785-22e3c4b3-5832-4ab4-a6cd-37bebe109cb4.png)
