### ISSUE TITLE
All Inertia requests must receive a valid Inertia response, however a plain JSON response was received.

### ISSUE THREAD

**Issue by kavinvalli** [eidellev/inertiajs-adonisjs#46]
When using the `Link` component from `@inertiajs/inertia-react`, i'm getting the following error
```
All Inertia requests must receive a valid Inertia response, however a plain JSON response was received.
```
<img width="1652" alt="Screenshot 2021-12-12 at 10 41 12 PM" src="https://user-images.githubusercontent.com/41034356/145722209-dd4ed30a-dc97-418e-93f6-f9d78712f917.png">

**Comment by eidellev** [comment]
@kavinvalli I see you closed the issue. can you share what was the solution?

**Comment by anishghimire862** [comment]
I think it's the same issue as discussed here: https://github.com/eidellev/inertiajs-adonisjs/issues/36
