### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by arthur-er** [eidellev/inertiajs-adonisjs#51]
# SSR Support for Inertia is officially out, and should be here as well

Currrently Inertia docs suggests running a separate server for rendering the pages as the official adapters don't run in NodeJS, but as Adonis is a NodeJS framework we can add support for Inertia SSR on the same server.

I'm currently using SSR without support from the adapter (using a view global that renders and returns the inertia page) and its working as a breeze.

My suggestion to implement this is just including a SSR Render config function on the already existing inertia config that receives the render function to support different front-end frameworks and include the SSR request in the existing @inertia edge tag with a extra @inertiaHead tag to match Inertia Laravel implementation

I'm willing to work in this if approved

**Comment by eidellev** [comment]
Thank you. I completely agree and was planing on starting to implement SSR later this week. If you have a working implementation and would like to open a PR that would be great.  Please note that I just added a contribution guide to the readme. 
Let me know if you have any questions. This is really exciting :-)

**Comment by arthur-er** [comment]
I don't know exactly how to fit it into the package, current it works like that:

```typescript
// start/view.ts
import View from '@ioc:Adonis/Core/View'

View.global('ssr', (page) => {
  try {
    return createInertiaApp({
      resolve: (name: string) => require(`Resources/Pages/${name}`).default,
      page,
      render: ReactDOMServer.renderToString,
      setup: ({ App, props }) => React.createElement(App, processProps(props)),
    })
  } catch (error) {
    return undefined
  }
})
```

```html
@set('ssr_page', await ssr(page))
<!DOCTYPE html>
<html>
  <head>
    @each(element in ssr_page?.head)
      {{{ element }}}
    @end
  </head>
  <body>
    @if(ssr_page)
      {{{ ssr_page.body }}}
    @else
      @inertia()
    @end
  </body>
</html>
```

**Comment by kevin-DL** [comment]
> I don't know exactly how to fit it into the package, current it works like that:
> 
> ```ts
> // start/view.ts
> import React from 'react'
> import ReactDOMServer from 'react-dom/server'
> import View from '@ioc:Adonis/Core/View'
> 
> View.global('ssr', (page) => {
>   try {
>     return createInertiaApp({
>       resolve: (name: string) => require(`Resources/Pages/${name}`).default,
>       page,
>       render: ReactDOMServer.renderToString,
>       setup: ({ App, props }) => React.createElement(App, processProps(props)),
>     })
>   } catch (error) {
>     return undefined
>   }
> })
> ```
> 
> ```
> @set('ssr_page', await ssr(page))
> <!DOCTYPE html>
> <html>
>   <head>
>     @each(element in ssr_page?.head)
>       {{{ element }}}
>     @end
>   </head>
>   <body>
>     @if(ssr_page)
>       {{{ ssr_page.body }}}
>     @else
>       @inertia()
>     @end
>   </body>
> </html>
> ```

Hello, this looks great, would it work the same way for Vue?

**Comment by arthur-er** [comment]
Yes, just swap the react part of inertia setup for the vue ones

**Comment by kevin-DL** [comment]
Thank you I will try that.

**Comment by justDare** [comment]
Any update on this one for out-of-the-box package support? Or does anyone have a working example they'd be open to sharing?

I'm close to a working react example I'd be able to share but still running into some webpack issues with TSX files.

**Comment by eidellev** [comment]
@justDare official support is coming eventually (I just had a busy couple of months with the whole covid-19 situation).
meanwhile, if you manage to make things work with your react example I'd be happy if you would consider opening a PR.

**Comment by eidellev** [comment]
SSR support for react was added in 6.1.0
Vue and svelte will be added soon
I'm keeping this ticket open until then

@arthur-er thank you for you example code, it really helped!

**Comment by EsTharian** [comment]
SSR support breaks the others, mine is Svelte and I got below error. @eidellev 
![image](https://user-images.githubusercontent.com/25347659/160256232-a6ce1b56-d21a-41b1-8eae-be86c6ae983e.png)

**Comment by eidellev** [comment]
@EsTharian thank you for reporting this. i'm already working on a fix + support for vue3.
meanwhile you can safely downgrade.

**Comment by bradley-varol** [comment]
> Vue and svelte will be added soon

Sorry to be *that guy* but is there an ETA on the Vue SSR support? I'm about to start a project and want to make sure it's going to be supported. Thanks 🙌🏻

**Comment by eidellev** [comment]
It's a little hard for me to commit to a timeline, this being a side project of mine, but support for Vue is coming.

**Comment by eidellev** [comment]
Vue is officially supported in v7.0.0 onward! 🥳
