### ISSUE TITLE
File upload problem witn react, inertia and adonis

### ISSUE THREAD

**Issue by dmostafiz** [eidellev/inertiajs-adonisjs#52]
Hello, i am just started with inertia react and adonis js. it seems everything okay, but when i am trying to upload file following inertia js official documentation i found and error like 

"**index.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')**"

and from the controller i am not getting any file reference to work with. if i am wrong anywhere to implement that, please guide me.

**Comment by eidellev** [comment]
Hi @dmostafiz 
Thanks for reporting this issue. I will check it out.

**Comment by dmostafiz** [comment]
Thanks for your reply, i hope the issue will be solved soon.

**Comment by eidellev** [comment]
After looking into the issue it seems to be a problem with Inertia's file upload documentation for react. 
This worked for me:
```typescript
import React from 'react';
import { useForm } from '@inertiajs/inertia-react';

export const UserForm = function () {
  const { data, setData, post, progress } = useForm<{ name: string; avatar: File }>({
    name: undefined,
    avatar: undefined,
  });

  function submit(e) {
    e.preventDefault();
    post('/users');
  }

  return (
    <form onSubmit={submit}>
      <input
        type="text"
        value={data.name || ''}
        onChange={(e) => setData('name', e.target.value)}
      />
      <input type="file" onChange={(e) => setData('avatar', e.target.files[0])} />
      {progress && (
        <progress value={progress.percentage} max="100">
          {progress.percentage}%
        </progress>
      )}
      <button type="submit">Submit</button>
    </form>
  );
};
```

> The main issue seems to be that you can't assign a value to a `file` input.

This is how I handled it on the backend:
```typescript
Route.post('/users', async ({ request, inertia }) => {
  const avatar = request.file('avatar');

  if (avatar) {
    await avatar.move(Application.tmpPath('uploads'));
  }

  return inertia.redirectBack();
});
```

Feel free to reopen this issue if you run into additional problems.

**Comment by dmostafiz** [comment]
I am doing same. just one different thing is i am not using typeScript in react.

But i am getting null in the controller endpoint.

Console log
![Screenshot 2022-02-19 230536](https://user-images.githubusercontent.com/62952421/154811165-d46a3b93-5480-4296-9c25-f0bd67729cd5.png)

React Component
![Screenshot 2022-02-19 230618](https://user-images.githubusercontent.com/62952421/154811188-8975a7e5-078e-48d2-8757-95e91d675d37.png)

Controller
![Screenshot 2022-02-19 230719](https://user-images.githubusercontent.com/62952421/154811202-86991301-2e80-4825-adda-4a89def54374.png)
