### ISSUE TITLE
Using vue still requires React from Inertia.js

### ISSUE THREAD

**Issue by GustavoFenilli** [eidellev/inertiajs-adonisjs#58]
Running after instalation and using the vue 3 provider still gives `Cannot find module 'react'` probably related to having a hard import on [React and ReactDomServer](https://github.com/eidellev/inertiajs-adonisjs/blob/main/src/Inertia.ts#L15-L16)

**Comment by eidellev** [comment]
Thanks @GustavoFenilli 
A fix is already in the works. I'm aiming for a release a bit later this week.

**Comment by eidellev** [comment]
fixed in `v6.1.1`
