### ISSUE TITLE
The ace config should also add the script tag.

### ISSUE THREAD

**Issue by GustavoFenilli** [eidellev/inertiajs-adonisjs#59]
When running the ace command to configure inertiajs-adonisjs it creates without `<script src="{{ asset('assets/app.js') }}" defer></script>` so it doesn't work at all.

Both the script for creating the app.edge and the docs should mention that this file is necessary.

**Comment by eidellev** [comment]
Thanks @GustavoFenilli 
I'll add this in a future release 👍

**Comment by eidellev** [comment]
added in `v6.2.0`
