### ISSUE TITLE
[ help wanted ]: Unexpected token '<'

### ISSUE THREAD

**Issue by KimhoutSam** [eidellev/inertiajs-adonisjs#61]
what should i do to get server side rendering?

**Comment by eidellev** [comment]
Hi @KimhoutSam 
Assuming you are using `react` you change the following in your `tsconfig`:
```json
...
"jsx": "react",
...
```

I'm closing this issue for now, but feel free to re-open if things still don't work for you.

**Comment by KimhoutSam** [comment]
But my appusing react ts
