### ISSUE TITLE
How to use Typescript Component?

### ISSUE THREAD

**Issue by hasib-workspacify** [eidellev/inertiajs-adonisjs#65]
If I try to make my component script lang="ts" it returns an error.

```
Module parse failed: Unexpected token (5:27)
File was processed with these loaders:
 * ./node_modules/vue-loader/dist/templateLoader.js
 * ./node_modules/vue-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
 * ./node_modules/vue-loader/dist/templateLoader.js
 * ./node_modules/vue-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
| const _hoisted_1 = { class: "flex" }
|
> export function render(_ctx: any,_cache: any,$props: any,$setup: any,$data: any,$options: any) {|   return (_openBlock(), _createElementBlock("div", _hoisted_1, [|     _createCommentVNode(" Sidebar "),
```

**Comment by eidellev** [comment]
Hi @hasib-workspacify
I don't think this is an inertia issue. You seem to be missing some config and probably need to install an additional webpack loader.  Please refer to the webpack-encore docs:
https://symfony.com/doc/current/frontend/encore/vuejs.html

P.S. if you think this is an issue with this library feel free to re-open this ticket with some additional information

**Comment by hasib-workspacify** [comment]
Could you please delete this issue?
