### ISSUE TITLE
how can get route info?

### ISSUE THREAD

**Issue by hasib-workspacify** [eidellev/inertiajs-adonisjs#66]
If you're using Laravel, the [Ziggy](https://github.com/tightenco/ziggy) library does this for you automatically via a global route() function. If you're using Ziggy with Vue, it's helpful to make this function available as a custom $route property so you can use it directly in your templates.

How can I do exact same thing in Adonis project?

**Comment by eidellev** [comment]
Hi @hasib-workspacify 
For adonis you have a similar library called [stardust](https://www.npmjs.com/package/@eidellev/adonis-stardust)
