### ISSUE TITLE
Flash message not found

### ISSUE THREAD

**Issue by arnauddoub** [eidellev/inertiajs-adonisjs#67]
Hello, I am trying to use the quick messages but they do not appear. Did I forget something?

Controller
![Screenshot 2022-05-25 at 10 52 37](https://user-images.githubusercontent.com/14277978/170223884-55e00461-1ab3-43df-8189-b548ba2bed41.png)

start/inertia.ts
![Screenshot 2022-05-25 at 10 52 46](https://user-images.githubusercontent.com/14277978/170224045-9c1a2f1f-f5e8-4934-8169-3233f65ad3f9.png)

And i print `{{  $page }}`
<img width="384" alt="Screenshot 2022-05-25 at 10 53 29" src="https://user-images.githubusercontent.com/14277978/170224159-0aa5ff67-a8c2-4928-b7c1-4261f0351d86.png">

but in the doc of inertiajs
<img width="639" alt="Screenshot 2022-05-25 at 10 59 03" src="https://user-images.githubusercontent.com/14277978/170224286-9854fc90-803d-46b4-bb19-7caa28d2357d.png">

I don't have the flash object

**Comment by anishghimire862** [comment]
Update your `start/inertia.ts` with the following code as well:

```
  flash: ({ session }) => {
    return session.flashMessages.all()
  }
```
