### ISSUE TITLE
All Inertia requests must receive a valid Inertia response, however a plain JSON response was received.

### ISSUE THREAD

**Issue by jakemake** [eidellev/inertiajs-adonisjs#70]
There is an error _All Inertia requests must receive a valid Inertia response, however a plain JSON response was received_. after updating adapter from version 4 to 6 
AddonisJS : "@adonisjs/core": "^5.8.3",
    "@eidellev/inertia-adonisjs": "^6.2.0",
    "@inertiajs/inertia": "^0.11.0",
    "@inertiajs/inertia-vue": "^0.8.0",

VUE version 2

But if i create a new Adonis App and use adapter v6 all works
![image](https://user-images.githubusercontent.com/22964241/173330243-43165cac-2924-435b-b2a1-afe19412d5ab.png)

**Comment by eidellev** [comment]
Hi @jakemake !
Sorry for the delayed response. I suspect that you are missing the inertia middleware in your config. Can you please confirm?

**Comment by eidellev** [comment]
Closing this for now. Feel free to reopen if this issue continues.

**Comment by jakemake** [comment]
everything

> Hi @jakemake ! Sorry for the delayed response. I suspect that you are missing the inertia middleware in your config. Can you please confirm?

i checked 2 project, one of them using v4 another v6 and didn't find differences except `.version(() => Inertia.manifestFile('public/assets/manifest.json'));`  in inertia share file.
