### ISSUE TITLE
Can we use Vite instead of Webpack?

### ISSUE THREAD

**Issue by caturandi-labs** [eidellev/inertiajs-adonisjs#78]
Hi @eidellev , is it possible to use vite? instead of webpack?

**Comment by eidellev** [comment]
Hi @caturandi-labs !
The short answer is yes. You can find an example [here](https://github.com/MichaelNZ85/AdonisVueViteInertia).
The long answer is making that SSR work with vite may not be as straightforward.

**Comment by matthewjumpsoffbuildings** [comment]
@eidellev is it still the case that vite and SSR dont play nice? And if not are there any plans to attempt to make it work?
