### ISSUE TITLE
How to use css in vue3 and ssr

### ISSUE THREAD

**Issue by fengzi91** [eidellev/inertiajs-adonisjs#82]
How to include the css file `inertia/ssr/ssr.css` in `app.edge`?
Thanks.

**Comment by eidellev** [comment]
@fengzi91 to the best of my understanding you don't need to include it at all since it's identical to your regular `app.css`. 
I need to investigate how this is handled in laravel for comparison.

Is there a reason you need to include `ssr.css` and not `app.css`?

**Comment by fengzi91** [comment]
this is an example project https://github.com/fengzi91/adonis-inertia-vue-ssr.git
