### ISSUE TITLE
@inertiaHead don't work

### ISSUE THREAD

**Issue by Reptiluka** [eidellev/inertiajs-adonisjs#85]
Hi ! I use import { Head } from '@inertiajs/inertia-vue3' i think, and the content i put in <Head></Head> , is rendered inside the div of the app as a <head> tag, but not added in the <head> where @inertiaHead is placed.

I use SSR, do you have an idea ?

Thanks !

**Comment by Reptiluka** [comment]
I was trying to include a component inside my <Head> tag, and it was render as <[object Object] inertia> 
But if i put the Head component, in the child component instead, it works i think, i don't know if it's on your side or not

**Comment by Reptiluka** [comment]
![image](https://user-images.githubusercontent.com/26306696/186965246-10afc4cf-3e06-4b96-b3e4-0a1a4be689d9.png)
Now the <Head> content is at the right place, but with comma ( , ) when rendered in SSR

**Comment by Reptiluka** [comment]
And with that bug, when the client side code load, it put also , the same meta tag in the <body> :/

**Comment by eidellev** [comment]
Thanks for reporting this issue @Reptiluka 
I will investigate and let you know when it's solved

**Comment by KimhoutSam** [comment]
> ![image](https://user-images.githubusercontent.com/26306696/186965246-10afc4cf-3e06-4b96-b3e4-0a1a4be689d9.png)
> Now the < Head > content is at the right place, but with comma ( , ) when rendered in SSR

I got that too.

**Comment by eidellev** [comment]
@KimhoutSam thanks! 
I solved the issue with the comma in v7.0.1

@Reptiluka I couldn't reproduce the issue you reported client-side with the react adapter so I suspect it's a problem with the inertia Vue3 adapter or that perhaps it's something on your end (I haven't used vue in years so I'm not super confident about this).  Either way, feel free to open another issue if you run into further issues.

**Comment by Reptiluka** [comment]
> @KimhoutSam thanks! I solved the issue with the comma in v7.0.1
> 
> @Reptiluka I couldn't reproduce the issue you reported client-side with the react adapter so I suspect it's a problem with the inertia Vue3 adapter or perhaps something on your end (I haven't used vue in years so I'm not super confident about this). Either way, feel free to open another issue if you run into additional trouble.

It's me who reported the issue with the comma haha 🙃 kimhoutsam just saying he had the same problem.

Thank you for the fix ! 😀
