### ISSUE TITLE
Does this work using Typescript in Svelte?

### ISSUE THREAD

**Issue by ikudosi** [eidellev/inertiajs-adonisjs#91]
I got this whole thing to work with Svelte, however, when I try to use `lang="ts"` in the .svelte files, I'm just getting numerous errors like an imported custom component not found etc.

I'm not sure if this is more of a Typescript config issue or something else?

**Comment by eidellev** [comment]
Hi @ikudosi 
I don't think this is an issue directly related to this library, but as a general rule of thumb you should probably have a separate `tsconfig.json` for your frontend.

I'm not very experienced with svelte, but in my react project I also ran into similar issues and it helped.

**Comment by ikudosi** [comment]
Can you kindly share your webpack config to have it load Typescript with
encore? Sorry just got onto Typescript and completely overwhelmed with all
this.

**Comment by eidellev** [comment]
to enable typescript you simply need to add this in your encore config:
```diff
  Encore
      // ...
+     .addEntry('main', './assets/main.ts')

+     .enableTypeScriptLoader()
```
https://symfony.com/doc/current/frontend/encore/typescript.html

this article shows an example of setting up svelte with encore webpack
https://www.twilio.com/blog/develop-a-symfony-app-using-svelte-and-webpack-encore-to-manage-your-twilio-message-history

hope this helps :-)

**Comment by ikudosi** [comment]
Thank you for pointing me in the right direction!!! Finally got it to
compile properly with Adonis!

1) Added the following packages - @tsconfig/svelte, ts-loader.
2) Changed webpack.config.js to have - Encore.addEntry('app',
'./resources/js/app.ts').enableTypeScriptLoader().
3) Created a tsconfig.json in my resources/js folder where my entry-point
(app.ts) is also located.

// tsconfig.json
{
  "extends": ***@***.***/svelte/tsconfig.json",
  "include": ["**/*"],
  "exclude": ["node_modules/*","public/*"],
  "compilerOptions": {
    "target": "ES6",
    "module": "ES2022"
  }
}
